# Generated by Django 3.2.19 on 2023-06-21 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisprudencias',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_causa', models.CharField(max_length=1)),
                ('rol', models.CharField(max_length=10)),
                ('caratula', models.CharField(max_length=100)),
                ('nombre_Proyecto', models.CharField(max_length=50)),
                ('fecha_sentencia', models.DateField()),
                ('descriptores', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None), size=None)),
                ('decision_del_tribunal', models.CharField(max_length=10)),
                ('competencia', models.CharField(max_length=20)),
                ('ministro_redactor', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
    ]
