# Generated by Django 3.2.19 on 2023-06-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='competencia',
            field=models.CharField(max_length=50),
        ),
    ]
