# Generated by Django 3.2.19 on 2023-06-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_jurisprudencias_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='competencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='nombre_Proyecto',
            field=models.CharField(max_length=100),
        ),
    ]
