# Generated by Django 3.2.19 on 2023-06-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20230621_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='caratula',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='competencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='nombre_Proyecto',
            field=models.CharField(max_length=255),
        ),
    ]
