# Generated by Django 3.2.19 on 2023-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_jurisprudencias_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='decision_del_tribunal',
            field=models.CharField(max_length=15),
        ),
    ]
