# Generated by Django 3.2.19 on 2023-06-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_jurisprudencias_decision_del_tribunal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='decision_del_tribunal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
