# Generated by Django 3.2.19 on 2023-06-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20230621_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisprudencias',
            name='tipo_recurso',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='tipo_causa',
            field=models.CharField(max_length=15),
        ),
    ]
