# Generated by Django 3.2.19 on 2023-06-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_jurisprudencias_tipo_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisprudencias',
            name='tribunal',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
