# Generated by Django 3.2.19 on 2023-06-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_jurisprudencias_tribunal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisprudencias',
            name='tipo',
        ),
    ]
