# Generated by Django 3.2.19 on 2023-06-22 06:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_remove_jurisprudencias_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='descriptores',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None),
        ),
    ]
